## Understand raw data

In [1]:
import pandas as pd
import numpy as np

### load files

In [3]:
matches=pd.read_csv("../data/matches.csv")
deliveries=pd.read_csv("../data/deliveries.csv")

### load first 5 rows

In [5]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

### check the data sets

In [7]:
print("Matches shape :",matches.shape)
print("Deliveries shape :",deliveries.shape)

Matches shape : (1095, 20)
Deliveries shape : (260920, 17)

In [8]:
# check column names

print("MATCHE COLUMNS")
print(matches.columns)
print("DELIVERIES COLUMNS")
print(deliveries.columns)

MATCHE COLUMNS
Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')
DELIVERIES COLUMNS
Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [9]:
#  check data types

matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 352.4 KB

In [10]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 50.4 MB

### identify the no of seasons

In [ ]:
matches["season"].nunique()

17

### identify the no of matches

In [15]:
print("TOTAL MATCHES")
matches["id"].nunique()

TOTAL MATCHES

1095

In [16]:
len(matches)

1095

### identify the total teams

In [19]:
teams = set(matches["team1"].dropna())|set(matches["team2"].dropna())
print("Total teams: ",len(teams))
print("\nTeams: ")
for team in teams:
    print(team)

Total teams:  19

Teams:
Rising Pune Supergiant
Deccan Chargers
Gujarat Titans
Pune Warriors
Royal Challengers Bangalore
Kochi Tuskers Kerala
Sunrisers Hyderabad
Rising Pune Supergiants
Royal Challengers Bengaluru
Kolkata Knight Riders
Delhi Daredevils
Rajasthan Royals
Punjab Kings
Kings XI Punjab
Mumbai Indians
Chennai Super Kings
Gujarat Lions
Delhi Capitals
Lucknow Super Giants

In [ ]:
### identify total venus

In [20]:
print("Total Venues :",
      matches["venue"].nunique())

Total Venues : 58

In [21]:
sorted(matches["venue"].dropna().unique())

['Arun Jaitley Stadium',
 'Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M Chinnaswamy Stadium, Bengaluru',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Maharashtra Cricket Association Stadium',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Punjab Cricket Association Stadium, Mohali',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

### identify total players

In [28]:
batsman=set(deliveries["batter"].dropna())
print("No Of batsmens : ",len(batsman))
bowlers=set(deliveries["bowler"].dropna())
print("No Of bowlers: ",len(bowlers))

players=batsman|bowlers
print("Total Players: ",len(players))

No Of batsmens :  673
No Of bowlers:  530
Total Players:  732

### check missing values

In [30]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [33]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [34]:
print(matches.isnull().mean()*100)
print(deliveries.isnull().mean()*100)

id                  0.000000
season              0.000000
city                4.657534
date                0.000000
match_type          0.000000
player_of_match     0.456621
venue               0.000000
team1               0.000000
team2               0.000000
toss_winner         0.000000
toss_decision       0.000000
winner              0.456621
result              0.000000
result_margin       1.735160
target_runs         0.273973
target_overs        0.273973
super_over          0.000000
method             98.082192
umpire1             0.000000
umpire2             0.000000
dtype: float64
match_id             0.000000
inning               0.000000
batting_team         0.000000
bowling_team         0.000000
over                 0.000000
ball                 0.000000
batter               0.000000
bowler               0.000000
non_striker          0.000000
batsman_runs         0.000000
extra_runs           0.000000
total_runs           0.000000
extras_type         94.586463
is_wicket            0.000000
player_dismissed    95.036793
dismissal_kind      95.036793
fielder             96.414993
dtype: float64

### check duplicates

In [35]:
print("Total rows:", len(matches))
print("Unique match IDs:", matches["id"].nunique())
print("Duplicate match IDs:", matches["id"].duplicated().sum())

Total rows: 1095
Unique match IDs: 1095
Duplicate match IDs: 0

### check date range

In [36]:
matches["date"].min(),matches["date"].max()

('2008-04-18', '2024-05-26')

### BASIC DATA QUALITY REPORT

In [37]:
print("========== IPL DATASET SUMMARY ==========")

print("Total Seasons :", matches["season"].nunique())
print("Total Matches :", matches["id"].nunique())
print("Total Teams   :", len(teams))
print("Total Venues  :", matches["venue"].nunique())
print("Total Players :", len(players))
print("Total Deliveries:", len(deliveries))

========== IPL DATASET SUMMARY ==========
Total Seasons : 17
Total Matches : 1095
Total Teams   : 19
Total Venues  : 58
Total Players : 732
Total Deliveries: 260920

## Data Cleaning

In [39]:
# MAKE COPIES

matches_clean=matches.copy()
deliveries_clean=deliveries.copy()
print("Copies created successfully")

Copies created successfully

In [40]:
# STANDARDIZWD COLUMN NAMES
matches_clean.columns=(matches_clean.columns.str.strip().str.lower().str.replace(" ","_"))
deliveries_clean.columns=(deliveries_clean.columns.str.strip().str.lower().str.replace(" ","_"))

print(matches_clean.columns.tolist())
print(deliveries_clean.columns.tolist())

['id', 'season', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2']
['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder']

In [41]:
# REMOVE UNNECESSARY SPACES

In [42]:
for df in [matches_clean,deliveries_clean]:
    text_columns=df.select_dtypes(include="object").columns
    for col in text_columns:
        df[col]=df[col].str.strip()

print("Text Field Standaerdized")

Text Field Standaerdized

C:\Users\chint\AppData\Local\Temp\ipykernel_16124\1720658393.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns=df.select_dtypes(include="object").columns
C:\Users\chint\AppData\Local\Temp\ipykernel_16124\1720658393.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns=df.select_dtypes(include="object").columns

In [44]:
# STANDARDIZE TEAM NAMES

team_mapping = {
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Rising Pune Supergiants": "Rising Pune Supergiant",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru"
}

In [45]:
matches_clean["team1"] = matches_clean["team1"].replace(team_mapping)
matches_clean["team2"] = matches_clean["team2"].replace(team_mapping)
matches_clean["toss_winner"] = matches_clean["toss_winner"].replace(team_mapping)
matches_clean["winner"] = matches_clean["winner"].replace(team_mapping)
deliveries_clean["batting_team"] = deliveries_clean["batting_team"].replace(team_mapping)
deliveries_clean["bowling_team"] = deliveries_clean["bowling_team"].replace(team_mapping)

In [46]:
# STANDERDIZED VENUE NAMES
sorted(matches["venue"].dropna().unique())

['Arun Jaitley Stadium',
 'Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M Chinnaswamy Stadium, Bengaluru',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Maharashtra Cricket Association Stadium',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Punjab Cricket Association Stadium, Mohali',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [51]:
venue_mapping={"Arun Jaitley Stadium":"Arun Jaitley Stadium, Delhi",
               "Brabourne Stadium":"Brabourne Stadium,Mumbai",
               "Dr DY Patil Sports Academy":"Dr DY Patil Sports Academy, Mumbai",
               "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium":"Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",
               "Eden Gardens":"Eden Gardens, Kolkata",
               "Himachal Pradesh Cricket Association Stadium":"Himachal Pradesh Cricket Association Stadium, Dharamsala",
               "M Chinnaswamy Stadium":"M Chinnaswamy Stadium, Bengaluru",
               "M.Chinnaswamy Stadium":"M Chinnaswamy Stadium, Bengaluru",
               "MA Chidambaram Stadium, Chepauk":"MA Chidambaram Stadium, Chepauk, Chennai",
               "MA Chidambaram Stadium":"MA Chidambaram Stadium, Chepauk, Chennai",
               "Maharashtra Cricket Association Stadium":"Maharashtra Cricket Association Stadium, Pune",
               "Punjab Cricket Association Stadium, Mohali":"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
               "Punjab Cricket Association IS Bindra Stadium, Mohali":"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
               "Punjab Cricket Association IS Bindra Stadium":"Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
               "Rajiv Gandhi International Stadium, Uppal":"Rajiv Gandhi International Stadium, Uppal, Hyderabad",
               "Rajiv Gandhi International Stadium":"Rajiv Gandhi International Stadium, Uppal, Hyderabad",
               "Wankhede Stadium":"Wankhede Stadium, Mumbai",
               "Sawai Mansingh Stadium":"Sawai Mansingh Stadium, Jaipur",
               "Sheikh Zayed Stadium":"Zayed Cricket Stadium, Abu Dhabi",
               }

In [52]:
matches_clean["venue"] = matches_clean["venue"].replace(venue_mapping)

In [53]:
sorted(matches_clean["venue"].dropna().unique())

['Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium, Mumbai',
 'Brabourne Stadium,Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium, Bengaluru',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [58]:
sorted(matches_clean["city"].dropna().unique())

['Abu Dhabi',
 'Ahmedabad',
 'Bangalore',
 'Bengaluru',
 'Bloemfontein',
 'Cape Town',
 'Centurion',
 'Chandigarh',
 'Chennai',
 'Cuttack',
 'Delhi',
 'Dharamsala',
 'Dubai',
 'Durban',
 'East London',
 'Guwahati',
 'Hyderabad',
 'Indore',
 'Jaipur',
 'Johannesburg',
 'Kanpur',
 'Kimberley',
 'Kochi',
 'Kolkata',
 'Lucknow',
 'Mohali',
 'Mumbai',
 'Nagpur',
 'Navi Mumbai',
 'Port Elizabeth',
 'Pune',
 'Raipur',
 'Rajkot',
 'Ranchi',
 'Sharjah',
 'Visakhapatnam']

In [59]:
# CONVERY DATYPE INTO DATE

matches_clean["date"] = pd.to_datetime(
    matches_clean["date"],
    errors="coerce"
)

print("Date type:", matches_clean["date"].dtype)

Date type: datetime64[us]

In [60]:
# CHECK DUPLICATES

print("Duplicate match IDs:",
      matches_clean["id"].duplicated().sum())

print("Duplicate match rows:",
      matches_clean.duplicated().sum())

print("Duplicate delivery rows:",
      deliveries_clean.duplicated().sum())

Duplicate match IDs: 0
Duplicate match rows: 0
Duplicate delivery rows: 0

In [62]:
matches_clean.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [63]:
# HANDLI MISSING CITY 

matches_clean[matches_clean["city"].isna()][
    ["id", "venue", "city"]
]

          id                                venue city
399   729281              Sharjah Cricket Stadium  NaN
402   729287  Dubai International Cricket Stadium  NaN
403   729289  Dubai International Cricket Stadium  NaN
404   729291              Sharjah Cricket Stadium  NaN
406   729295              Sharjah Cricket Stadium  NaN
407   729297  Dubai International Cricket Stadium  NaN
408   729299              Sharjah Cricket Stadium  NaN
409   729301  Dubai International Cricket Stadium  NaN
410   729303  Dubai International Cricket Stadium  NaN
413   729309              Sharjah Cricket Stadium  NaN
414   729311              Sharjah Cricket Stadium  NaN
415   729313  Dubai International Cricket Stadium  NaN
417   729317  Dubai International Cricket Stadium  NaN
757  1216493  Dubai International Cricket Stadium  NaN
758  1216534  Dubai International Cricket Stadium  NaN
759  1216496              Sharjah Cricket Stadium  NaN
761  1216510  Dubai International Cricket Stadium  NaN
762  1216539  Dubai International Cricket Stadium  NaN
764  1216527              Sharjah Cricket Stadium  NaN
765  1216547  Dubai International Cricket Stadium  NaN
767  1216504  Dubai International Cricket Stadium  NaN
769  1216516  Dubai International Cricket Stadium  NaN
771  1216515              Sharjah Cricket Stadium  NaN
772  1216513  Dubai International Cricket Stadium  NaN
773  1216538              Sharjah Cricket Stadium  NaN
774  1216519  Dubai International Cricket Stadium  NaN
777  1216542  Dubai International Cricket Stadium  NaN
778  1216500              Sharjah Cricket Stadium  NaN
780  1216525  Dubai International Cricket Stadium  NaN
781  1216507  Dubai International Cricket Stadium  NaN
783  1216540              Sharjah Cricket Stadium  NaN
784  1216528  Dubai International Cricket Stadium  NaN
785  1216543  Dubai International Cricket Stadium  NaN
786  1216531              Sharjah Cricket Stadium  NaN
788  1216509              Sharjah Cricket Stadium  NaN
789  1216522  Dubai International Cricket Stadium  NaN
791  1216517  Dubai International Cricket Stadium  NaN
793  1216546  Dubai International Cricket Stadium  NaN
795  1216518  Dubai International Cricket Stadium  NaN
796  1216521              Sharjah Cricket Stadium  NaN
798  1216498  Dubai International Cricket Stadium  NaN
800  1216544  Dubai International Cricket Stadium  NaN
801  1216520              Sharjah Cricket Stadium  NaN
802  1216524  Dubai International Cricket Stadium  NaN
804  1216536  Dubai International Cricket Stadium  NaN
806  1216502              Sharjah Cricket Stadium  NaN
807  1216535  Dubai International Cricket Stadium  NaN
809  1216530  Dubai International Cricket Stadium  NaN
811  1216495              Sharjah Cricket Stadium  NaN
812  1237177  Dubai International Cricket Stadium  NaN
815  1237181  Dubai International Cricket Stadium  NaN

In [71]:
venue_city_mapping = {
    "Sharjah Cricket Stadium": "Sharjah",
    "Dubai International Cricket Stadium": "Dubai"
}

matches_clean["city"] = (
    matches_clean["city"]
    .fillna(matches_clean["venue"].map(venue_city_mapping))
)

matches_clean["method_status"] = (
    matches_clean["method"].fillna("Normal")
)

In [72]:
matches_clean["city"].isna().sum()

np.int64(0)

###  Winner validation

In [73]:
invalid_winners = matches_clean[
    matches_clean["winner"].notna() &
    ~(
        (matches_clean["winner"] == matches_clean["team1"]) |
        (matches_clean["winner"] == matches_clean["team2"])
    )
]

print("Invalid winner records:", len(invalid_winners))

Invalid winner records: 0

### Toss winner validation

In [74]:
invalid_toss_winners = matches_clean[
    matches_clean["toss_winner"].notna() &
    ~(
        (matches_clean["toss_winner"] == matches_clean["team1"]) |
        (matches_clean["toss_winner"] == matches_clean["team2"])
    )
]

print("Invalid toss winner records:", len(invalid_toss_winners))

Invalid toss winner records: 0

### Referencial intigrity

In [75]:
match_ids = set(matches_clean["id"])

invalid_delivery_matches = deliveries_clean[
    ~deliveries_clean["match_id"].isin(match_ids)
]

print(
    "Deliveries with invalid match IDs:",
    len(invalid_delivery_matches)
)

Deliveries with invalid match IDs: 0

### Missing value report

In [76]:
missing_report = pd.DataFrame({
    "Column": matches_clean.columns,
    "Missing_Count": matches_clean.isnull().sum().values,
    "Missing_Percentage": (
        matches_clean.isnull().mean().values * 100
    ).round(2)
})

missing_report = missing_report.sort_values(
    by="Missing_Count",
    ascending=False
)

missing_report

             Column  Missing_Count  Missing_Percentage
17           method           1074               98.08
13    result_margin             19                1.74
5   player_of_match              5                0.46
11           winner              5                0.46
14      target_runs              3                0.27
15     target_overs              3                0.27
4        match_type              0                0.00
2              city              0                0.00
1            season              0                0.00
0                id              0                0.00
3              date              0                0.00
7             team1              0                0.00
6             venue              0                0.00
12           result              0                0.00
10    toss_decision              0                0.00
9       toss_winner              0                0.00
8             team2              0                0.00
16       super_over              0                0.00
18          umpire1              0                0.00
19          umpire2              0                0.00
20    method_status              0                0.00

### Delivery missing value report

In [77]:
delivery_missing_report = pd.DataFrame({
    "Column": deliveries_clean.columns,
    "Missing_Count": deliveries_clean.isnull().sum().values,
    "Missing_Percentage": (
        deliveries_clean.isnull().mean().values * 100
    ).round(2)
})

delivery_missing_report = delivery_missing_report.sort_values(
    by="Missing_Count",
    ascending=False
)

delivery_missing_report

              Column  Missing_Count  Missing_Percentage
16           fielder         251566               96.41
15    dismissal_kind         247970               95.04
14  player_dismissed         247970               95.04
12       extras_type         246795               94.59
0           match_id              0                0.00
1             inning              0                0.00
2       batting_team              0                0.00
3       bowling_team              0                0.00
4               over              0                0.00
8        non_striker              0                0.00
7             bowler              0                0.00
6             batter              0                0.00
5               ball              0                0.00
11        total_runs              0                0.00
10        extra_runs              0                0.00
9       batsman_runs              0                0.00
13         is_wicket              0                0.00

## Final quality summary

In [85]:
quality_summary = pd.DataFrame({
    "Dataset": ["Matches", "Deliveries"],
    "Rows": [
        len(matches_clean),
        len(deliveries_clean)
    ],
    "Columns": [
        len(matches_clean.columns),
        len(deliveries_clean.columns)
    ],
    "Duplicate_Rows": [
        matches_clean.duplicated().sum(),
        deliveries_clean.duplicated().sum()
    ],
    "Missing_Cells": [
        matches_clean.isnull().sum().sum(),
        deliveries_clean.isnull().sum().sum()
    ]
})

quality_summary

      Dataset    Rows  Columns  Duplicate_Rows  Missing_Cells
0     Matches    1095       21               0           1109
1  Deliveries  260920       17               0         994301

In [92]:
# FINAL QUALITY CHECK

final_quality = pd.DataFrame({
    "Check": [
        "Total Matches",
        "Total Deliveries",
        "Duplicate Match IDs",
        "Duplicate Match Rows",
        "Duplicate Delivery Rows",
        "Invalid Winners",
        "Invalid Toss Winners",
        "Invalid Delivery Match IDs",
        "Missing Dates",
        "Missing Cities"
    ],
    "Result": [
        len(matches_clean),
        len(deliveries_clean),
        matches_clean["id"].duplicated().sum(),
        matches_clean.duplicated().sum(),
        deliveries_clean.duplicated().sum(),
        len(invalid_winners),
        len(invalid_toss_winners),
        len(invalid_delivery_matches),
        matches_clean["date"].isna().sum(),
        matches_clean["city"].isna().sum()
    ]
})

final_quality

                        Check  Result
0               Total Matches    1095
1            Total Deliveries  260920
2         Duplicate Match IDs       0
3        Duplicate Match Rows       0
4     Duplicate Delivery Rows       0
5             Invalid Winners       0
6        Invalid Toss Winners       0
7  Invalid Delivery Match IDs       0
8               Missing Dates       0
9              Missing Cities       0

In [86]:
#  SAVE CLEANED FILES

In [87]:
matches_clean.to_csv(
    "../data/ipl_matches_clean.csv",
    index=False
)

deliveries_clean.to_csv(
    "../data/ipl_deliveries_clean.csv",
    index=False
)

print("Cleaned datasets saved successfully.")

Cleaned datasets saved successfully.

### create ipl_clean.csv

In [88]:
matches_clean.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2',
 'method_status']

In [89]:
#finalize columns

ipl_clean = matches_clean[[
    "id",
    "season",
    "city",
    "date",
    "match_type",
    "player_of_match",
    "venue",
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "winner",
    "result",
    "result_margin",
    "target_runs",
    "target_overs",
    "super_over",
    "method",
    "method_status"
]].copy()

In [90]:
# save data set

ipl_clean.to_csv(
    "../data/ipl_clean.csv",
    index=False
)

print("ipl_clean.csv created successfully!")

ipl_clean.csv created successfully!

In [91]:
# verify
print("Rows:", len(ipl_clean))
print("Columns:", len(ipl_clean.columns))

ipl_clean.head()

Rows: 1095
Columns: 19

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,method_status
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Normal
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association IS Bindra Stadium, ...",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,Normal
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,130.0,20.0,N,NaN,Normal
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,"Wankhede Stadium, Mumbai",Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,bat,Royal Challengers Bengaluru,wickets,5.0,166.0,20.0,N,NaN,Normal
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,"Eden Gardens, Kolkata",Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,Normal